name: Deploy Azure Function

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      slot:
        description: "Optional deployment slot name"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create deployment package (zip)
        run: |
          zip -r functionapp.zip . \
            -x "node_modules/*" \
               ".git/*" \
               ".github/*" \
               "local.settings.json" \
               "*.md"

      - name: Zip Deploy to Kudu (publish profile)
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        run: |
          set -euo pipefail
          # Extract host and credentials
          eval "$(python3 .github/scripts/parse_publish_profile.py)"
          echo "Using Kudu host: $KUDU_HOST"
          if [ -n "${{ github.event.inputs.slot }}" ]; then
            echo "Note: Slots require a slot-specific publish profile."
          fi
          # Perform zipdeploy with diagnostics
          ZIP_URL="https://$KUDU_HOST/api/zipdeploy?isAsync=true"
          echo "Posting to: $ZIP_URL"
          http_code=$(curl -sS -u "$KUDU_USER:$KUDU_PASS" \
                           -X POST \
                           -H "Content-Type: application/zip" \
                           --data-binary @functionapp.zip \
                           -D headers.txt \
                           -o body.txt \
                           -w "%{http_code}" \
                           "$ZIP_URL" || true)
          echo "Response code: $http_code"
          echo "--- Response headers ---" && sed -n '1,200p' headers.txt || true
          echo "--- Response body ---" && sed -n '1,200p' body.txt || true
          if [ "$http_code" != "200" ] && [ "$http_code" != "202" ]; then
            echo "ZipDeploy failed with HTTP $http_code" >&2
            exit 1
          fi

      - name: Warm up Function App
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        run: |
          eval "$(python3 .github/scripts/parse_publish_profile.py)"
          APP_HOST="${KUDU_HOST/.scm./.}"
          curl -sS --max-time 10 "https://${APP_HOST}" || true
